version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "anti-bruteforce"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
    ports:
      - "5432:5432"