app:
  name: "anti-bruteforce"
  version: '0.0.1'
  debug: true
http:
  port: ':8080'
logger:
  log_level: 'debug'
postgres:
  pool_max: 2
  url: "none" #postgres://...

bucket_limit:
  login_limit: 3
  password_limit: 10
  ip_limit: 1000