name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.21.1

      - name: Check out code
        uses: action/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          working-directory: .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.21.1

      - name: Chek out code
        uses: action/checkout@v3

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=1m ./...
        working-directory: .